/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coffee.Form;

import coffee.BLL.CartBLL;
import coffee.BLL.FileBLL;
import coffee.BLL.ProductBLL;
import coffee.DAL.BillDAL;
import coffee.DAL.CartDAL;
import coffee.DAL.OrderDAL;
import coffee.DAL.ProductDAL;
import coffee.DAL.StaffDAL;
import coffee.DAL.categoryDAL;
import coffee.DTO.BillDTO;
import coffee.DTO.CartDTO;
import coffee.DTO.MiniProductDTO;
import coffee.DTO.OrderDTO;
import coffee.DTO.ProductDTO;
import coffee.DTO.StaffDTO;
import coffee.DTO.categoryDTO;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.print.PrinterException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.view.*;
import net.sf.jasperreports.engine.*;

/**
 *
 * @author Hung Tuong Vy
 */
public final class CashierForm extends javax.swing.JFrame {

    /**
     * Creates new form CashierForm
     */
    private final int cashier_id;
    StaffDAL staff=new StaffDAL();
    StaffDTO StaffDTO=new StaffDTO();
    public CashierForm(int id) throws Exception {  
        this.cashier_id=id;
        StaffDTO=staff.getStaff(Integer.toString(cashier_id));
        initComponents();
        txtName.setText(StaffDTO.getFirstname()+" "+StaffDTO.getLastname());
        updateCategory();
        updatetabHistory();
        updateNotiIcon();
        tableUpdate();
        panelMain.removeAll();
        panelMain.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnOrder = new javax.swing.JButton();
        btnManage = new javax.swing.JButton();
        btnHistory = new javax.swing.JButton();
        lblNoti = new javax.swing.JLabel();
        lblNotiIcon = new javax.swing.JLabel();
        txtName = new javax.swing.JLabel();
        panelMain = new javax.swing.JPanel();
        panelHistory = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabHistory = new javax.swing.JTable();
        btnProperties = new javax.swing.JButton();
        panelProperties = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtBillID = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtDate = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabProperties = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txtCashierName = new javax.swing.JLabel();
        abc = new javax.swing.JLabel();
        txtTotal = new javax.swing.JLabel();
        btnExcel = new javax.swing.JButton();
        btnPDF = new javax.swing.JButton();
        panelManage = new javax.swing.JPanel();
        panelOrder = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtFind = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        boxCategory = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabProduct = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabAddToCart = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtSubTotal = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtPay = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtBalance = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        PanelNotif = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(246, 71, 71));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnOrder.setBackground(new java.awt.Color(246, 71, 71));
        btnOrder.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnOrder.setText("Order");
        btnOrder.setBorder(null);
        btnOrder.setBorderPainted(false);
        btnOrder.setContentAreaFilled(false);
        btnOrder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOrder.setOpaque(true);
        btnOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOrderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnOrderMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnOrderMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnOrderMouseReleased(evt);
            }
        });
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });
        jPanel6.add(btnOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 50));

        btnManage.setBackground(new java.awt.Color(246, 71, 71));
        btnManage.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnManage.setText("Manage");
        btnManage.setBorder(null);
        btnManage.setBorderPainted(false);
        btnManage.setContentAreaFilled(false);
        btnManage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManage.setOpaque(true);
        btnManage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnManageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnManageMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnManageMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnManageMouseReleased(evt);
            }
        });
        btnManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageActionPerformed(evt);
            }
        });
        jPanel6.add(btnManage, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 130, 50));

        btnHistory.setBackground(new java.awt.Color(246, 71, 71));
        btnHistory.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnHistory.setText("History");
        btnHistory.setBorder(null);
        btnHistory.setBorderPainted(false);
        btnHistory.setContentAreaFilled(false);
        btnHistory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHistory.setOpaque(true);
        btnHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHistoryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHistoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHistoryMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnHistoryMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnHistoryMouseReleased(evt);
            }
        });
        btnHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoryActionPerformed(evt);
            }
        });
        jPanel6.add(btnHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 130, 50));

        lblNoti.setBackground(new java.awt.Color(246, 71, 71));
        lblNoti.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNoti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_notification_24px_1.png"))); // NOI18N
        lblNoti.setOpaque(true);
        lblNoti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNotiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNotiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNotiMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblNotiMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblNotiMouseReleased(evt);
            }
        });
        jPanel6.add(lblNoti, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 0, 60, 50));

        lblNotiIcon.setBackground(new java.awt.Color(246, 71, 71));
        lblNotiIcon.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNotiIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_high_priority_16px.png"))); // NOI18N
        lblNotiIcon.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblNotiIcon.setOpaque(true);
        jPanel6.add(lblNotiIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 0, 90, 50));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1380, 50));

        txtName.setBackground(new java.awt.Color(255, 102, 102));
        txtName.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        txtName.setText("Nguyễn Hoàng Anh Hùng");
        txtName.setOpaque(true);
        txtName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtNameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtNameMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNameMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtNameMouseReleased(evt);
            }
        });
        jPanel2.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 90, 130, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, -1));

        panelMain.setBackground(new java.awt.Color(204, 204, 204));
        panelMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelHistory.setBackground(new java.awt.Color(204, 204, 204));
        panelHistory.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Date", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabHistory);

        panelHistory.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        btnProperties.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnProperties.setText("Properties");
        btnProperties.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPropertiesActionPerformed(evt);
            }
        });
        panelHistory.add(btnProperties, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, 80, -1));

        panelProperties.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Properties", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 3, 18))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel6.setText("No :");

        txtBillID.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        txtBillID.setForeground(new java.awt.Color(255, 0, 0));
        txtBillID.setText("12");

        jLabel8.setText("Date :");

        txtDate.setFont(new java.awt.Font("Trebuchet MS", 0, 10)); // NOI18N
        txtDate.setText("19/03/200");

        tabProperties.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product", "Size", "Qty", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tabProperties);

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel9.setText("Cashier :");

        txtCashierName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtCashierName.setForeground(new java.awt.Color(255, 0, 0));
        txtCashierName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        abc.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        abc.setText("Total");

        txtTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(255, 0, 0));
        txtTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelPropertiesLayout = new javax.swing.GroupLayout(panelProperties);
        panelProperties.setLayout(panelPropertiesLayout);
        panelPropertiesLayout.setHorizontalGroup(
            panelPropertiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
            .addGroup(panelPropertiesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPropertiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPropertiesLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCashierName, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPropertiesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelPropertiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPropertiesLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBillID, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPropertiesLayout.createSequentialGroup()
                                .addComponent(abc, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        panelPropertiesLayout.setVerticalGroup(
            panelPropertiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPropertiesLayout.createSequentialGroup()
                .addGroup(panelPropertiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPropertiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtBillID, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPropertiesLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(panelPropertiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDate)
                            .addComponent(jLabel9)
                            .addComponent(txtCashierName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPropertiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(abc)
                    .addComponent(txtTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        panelHistory.add(panelProperties, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, 590, 430));

        btnExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_microsoft_excel_100px.png"))); // NOI18N
        btnExcel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnExcelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnExcelMouseReleased(evt);
            }
        });
        btnExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcelActionPerformed(evt);
            }
        });
        panelHistory.add(btnExcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, 80, 70));

        btnPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_pdf_100px_2.png"))); // NOI18N
        btnPDF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPDFMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnPDFMouseReleased(evt);
            }
        });
        btnPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPDFActionPerformed(evt);
            }
        });
        panelHistory.add(btnPDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, 80, 80));

        panelMain.add(panelHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 520));

        javax.swing.GroupLayout panelManageLayout = new javax.swing.GroupLayout(panelManage);
        panelManage.setLayout(panelManageLayout);
        panelManageLayout.setHorizontalGroup(
            panelManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1390, Short.MAX_VALUE)
        );
        panelManageLayout.setVerticalGroup(
            panelManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        panelMain.add(panelManage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 520));

        panelOrder.setBackground(new java.awt.Color(204, 204, 204));
        panelOrder.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_search_32px.png"))); // NOI18N
        panelOrder.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(789, 101, -1, -1));

        txtFind.setBackground(new java.awt.Color(204, 204, 204));
        txtFind.setBorder(null);
        txtFind.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFindKeyPressed(evt);
            }
        });
        panelOrder.add(txtFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(829, 111, 200, 20));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_login_16px.png"))); // NOI18N
        jButton1.setText("Find");
        panelOrder.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1039, 106, -1, -1));

        boxCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        boxCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxCategoryActionPerformed(evt);
            }
        });
        panelOrder.add(boxCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(839, 71, 100, -1));
        panelOrder.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(829, 137, 200, 10));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Order");
        panelOrder.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 11, 114, -1));

        tabProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Barcode", "Product", "Size", "Qty", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabProduct);
        if (tabProduct.getColumnModel().getColumnCount() > 0) {
            tabProduct.getColumnModel().getColumn(0).setMinWidth(50);
            tabProduct.getColumnModel().getColumn(0).setMaxWidth(60);
            tabProduct.getColumnModel().getColumn(1).setMinWidth(250);
            tabProduct.getColumnModel().getColumn(1).setMaxWidth(300);
            tabProduct.getColumnModel().getColumn(2).setMinWidth(50);
            tabProduct.getColumnModel().getColumn(2).setMaxWidth(60);
            tabProduct.getColumnModel().getColumn(3).setMinWidth(50);
            tabProduct.getColumnModel().getColumn(3).setMaxWidth(60);
            tabProduct.getColumnModel().getColumn(4).setMinWidth(70);
            tabProduct.getColumnModel().getColumn(4).setMaxWidth(100);
        }

        panelOrder.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(751, 153, 582, 304));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add To Cart", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Serif", 2, 18))); // NOI18N

        tabAddToCart.setForeground(new java.awt.Color(255, 102, 102));
        tabAddToCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Barcode", "Product", "Size", "Note", "Qty", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabAddToCart.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(tabAddToCart);
        if (tabAddToCart.getColumnModel().getColumnCount() > 0) {
            tabAddToCart.getColumnModel().getColumn(0).setMinWidth(50);
            tabAddToCart.getColumnModel().getColumn(0).setMaxWidth(100);
            tabAddToCart.getColumnModel().getColumn(1).setMinWidth(200);
            tabAddToCart.getColumnModel().getColumn(1).setMaxWidth(300);
            tabAddToCart.getColumnModel().getColumn(2).setMinWidth(40);
            tabAddToCart.getColumnModel().getColumn(2).setMaxWidth(50);
            tabAddToCart.getColumnModel().getColumn(3).setMinWidth(70);
            tabAddToCart.getColumnModel().getColumn(4).setMinWidth(30);
            tabAddToCart.getColumnModel().getColumn(4).setMaxWidth(70);
        }

        jLabel5.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        jLabel5.setText("Sub Total : ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(213, 213, 213)
                        .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtSubTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                        .addGap(2, 2, 2)))
                .addGap(0, 7, Short.MAX_VALUE))
        );

        panelOrder.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 42, -1, 340));

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        panelOrder.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(638, 130, 70, -1));

        jButton3.setText("Edit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        panelOrder.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, 70, -1));

        jLabel3.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        jLabel3.setText("Pay :");
        panelOrder.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 42, -1));
        panelOrder.add(txtPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 223, -1));

        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jButton4.setText("Pay Invoice");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        panelOrder.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, -1, 22));

        jLabel4.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        jLabel4.setText("Balance :");
        panelOrder.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 74, 20));
        panelOrder.add(txtBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, 223, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("* Giá mỗi size sẽ được tự cập nhât - Staff chỉ cần chọn size");
        panelOrder.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(922, 468, 411, -1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        panelOrder.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1173, 25, -1, -1));

        jButton8.setText("Clear");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        panelOrder.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 250, 70, -1));

        panelMain.add(panelOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        PanelNotif.setBackground(new java.awt.Color(204, 204, 0));

        javax.swing.GroupLayout PanelNotifLayout = new javax.swing.GroupLayout(PanelNotif);
        PanelNotif.setLayout(PanelNotifLayout);
        PanelNotifLayout.setHorizontalGroup(
            PanelNotifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        PanelNotifLayout.setVerticalGroup(
            PanelNotifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        panelMain.add(PanelNotif, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 0, 410, 150));

        getContentPane().add(panelMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 1390, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageMouseEntered
        // TODO add your handling code here:
        btnManage.setBackground(new Color(214, 69, 65));
    }//GEN-LAST:event_btnManageMouseEntered

    private void btnManageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageMouseExited
        // TODO add your handling code here:
        btnManage.setBackground(new Color(246, 71, 71));
    }//GEN-LAST:event_btnManageMouseExited

    private void btnManageMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageMousePressed
        // TODO add your handling code here:
        btnManage.setBackground(new Color(255, 148, 120));
    }//GEN-LAST:event_btnManageMousePressed

    private void btnManageMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageMouseReleased
        // TODO add your handling code here:
        btnManage.setBackground(new Color(246, 71, 71));
    }//GEN-LAST:event_btnManageMouseReleased

    private void btnHistoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistoryMouseEntered
        // TODO add your handling code here:
        btnHistory.setBackground(new Color(214, 69, 65));
    }//GEN-LAST:event_btnHistoryMouseEntered

    private void btnHistoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistoryMouseExited
        // TODO add your handling code here:
        btnHistory.setBackground(new Color(246, 71, 71));
    }//GEN-LAST:event_btnHistoryMouseExited

    private void btnHistoryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistoryMousePressed
        // TODO add your handling code here:
        btnHistory.setBackground(new Color(255, 148, 120));
    }//GEN-LAST:event_btnHistoryMousePressed

    private void btnHistoryMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistoryMouseReleased
        // TODO add your handling code here:
        btnHistory.setBackground(new Color(246, 71, 71));
    }//GEN-LAST:event_btnHistoryMouseReleased

    private void btnOrderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOrderMouseEntered
        // TODO add your handling code here:
        btnOrder.setBackground(new Color(214, 69, 65));
    }//GEN-LAST:event_btnOrderMouseEntered

    private void btnOrderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOrderMouseExited
        // TODO add your handling code here:
        btnOrder.setBackground(new Color(246, 71, 71));
    }//GEN-LAST:event_btnOrderMouseExited

    private void btnOrderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOrderMousePressed
        // TODO add your handling code here:
        btnOrder.setBackground(new Color(255, 148, 120));
    }//GEN-LAST:event_btnOrderMousePressed

    private void btnOrderMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOrderMouseReleased
        // TODO add your handling code here:
        btnOrder.setBackground(new Color(246, 71, 71));
    }//GEN-LAST:event_btnOrderMouseReleased

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        try {
            // TODO add your handling code here:
            panelMain.removeAll();
            panelMain.repaint();
            panelMain.add(panelOrder);
            panelMain.revalidate();
        } catch (Exception ex) {
            Logger.getLogger(CashierForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnOrderActionPerformed

    private void btnManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageActionPerformed
        // TODO add your handling code here:
        panelMain.removeAll();
        panelMain.repaint();
        panelMain.add(panelManage);
        panelMain.revalidate();
    }//GEN-LAST:event_btnManageActionPerformed
    
    private void boxCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxCategoryActionPerformed
        try {
            // TODO add your handling code here:
            ArrayList<ProductDTO> ListProduct=new ArrayList<>();
            String Category=boxCategory.getSelectedItem().toString();
            ProductDAL productDAL=new ProductDAL();
            ListProduct=productDAL.getProduct_Category(Category);
            DefaultTableModel d=(DefaultTableModel) tabProduct.getModel();
            d.setRowCount(0);  
            
            for(int i=0;i<ListProduct.size();i++)
            {
                 if(ListProduct.get(i).getStatus()==1)
                 {
                     Vector v2=new Vector();
                    v2.add(ListProduct.get(i).getBarcode());
                    v2.add(ListProduct.get(i).getName());
                    v2.add(new ProductBLL().getSize(ListProduct.get(i).getSize()));
                    v2.add(ListProduct.get(i).getQty());
                    v2.add(ListProduct.get(i).getPrice());
                    d.addRow(v2);
                 }
            }
            
        } catch (Exception ex) {
            Logger.getLogger(CashierForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_boxCategoryActionPerformed
    
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            // TODO add your handling code here:
            DefaultTableModel d=(DefaultTableModel) tabProduct.getModel();
            int selectIndex=tabProduct.getSelectedRow();
            String Barcode=d.getValueAt(selectIndex, 0).toString();
            String name=d.getValueAt(selectIndex, 1).toString();
            String size=d.getValueAt(selectIndex, 2).toString() ;
            int qty=Integer.parseInt(d.getValueAt(selectIndex, 3).toString());
            int price=Integer.parseInt(d.getValueAt(selectIndex, 4).toString());
            int category_id=new ProductBLL().getCategoryId(boxCategory.getSelectedItem().toString());
            MiniProductDTO product=new MiniProductDTO(name, size, price, qty, Barcode,category_id);
            System.out.println(product.getCategory_id());
            new AddtoCart(product).setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(CashierForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            // TODO add your handling code here:
            int Money=Integer.parseInt(txtPay.getText().toString());
            int SubTotal=Integer.parseInt(txtSubTotal.getText().toString());
            int Balance=Money-SubTotal;
            txtBalance.setText(Integer.toString(Balance));
            txtBalance.setEnabled(false);
            String name=StaffDTO.getFirstname()+" "+StaffDTO.getLastname();
            new CartBLL().Print(name,SubTotal, Money, Balance, tabAddToCart.getModel());
            ArrayList<CartDTO> ListCart=new ArrayList<>();
            ListCart=new FileBLL().ReadFiletoList("C:\\Users\\hoang\\Desktop\\java\\Coffee\\temp.txt");
            CartBLL cartBLL=new CartBLL();
            cartBLL.createBill(cartBLL.BillMap(SubTotal));
            BillDTO bill=new CartDAL().getBill();
            for(int i=0;i<ListCart.size();i++)
            {
                cartBLL.insertData(cartBLL.getMap(ListCart.get(i), cashier_id, bill.getId()));
            }
            cartBLL.updateQty(ListCart);
            updatetabProduct();
            FileBLL file=new FileBLL();
            file.WriteFile_FW("C:\\Users\\hoang\\Desktop\\java\\Coffee\\temp.txt");
            tableUpdate();
            updateNotiIcon();
        } catch (PrinterException ex) {
            Logger.getLogger(CashierForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(CashierForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(CashierForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void lblNotiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNotiMouseEntered
        // TODO add your handling code here:
        lblNoti.setBackground(new Color(255, 148, 120));
    }//GEN-LAST:event_lblNotiMouseEntered

    private void lblNotiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNotiMousePressed
        // TODO add your handling code here:
        lblNoti.setBackground(new Color(214, 69, 65)); 
    }//GEN-LAST:event_lblNotiMousePressed

    private void lblNotiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNotiMouseExited
        // TODO add your handling code here:
        lblNoti.setBackground(new Color(246, 71, 71));
    }//GEN-LAST:event_lblNotiMouseExited

    private void lblNotiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNotiMouseReleased
        // TODO add your handling code here:
        lblNoti.setBackground(new Color(246, 71, 71));
    }//GEN-LAST:event_lblNotiMouseReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            // TODO add your handling code here:
            DefaultTableModel d=(DefaultTableModel) tabAddToCart.getModel();
            int selectIndex=tabAddToCart.getSelectedRow();
            String Barcode=d.getValueAt(selectIndex, 0).toString();
            String name=d.getValueAt(selectIndex, 1).toString();
            String size=d.getValueAt(selectIndex, 2).toString() ;
            String note=(d.getValueAt(selectIndex, 3).toString());
            int qty=Integer.parseInt(d.getValueAt(selectIndex, 4).toString());
            int price=Integer.parseInt(d.getValueAt(selectIndex, 5).toString());
            int category_id=new ProductBLL().getCategoryId(boxCategory.getSelectedItem().toString());
            MiniProductDTO product=new MiniProductDTO(name, size, price, qty, Barcode, category_id);
            System.out.println(product.getCategory_id());
            new DeleteItem(product,note).setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(CashierForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        try {
            // TODO add your handling code here:
            FileBLL file=new FileBLL();
            file.WriteFile_FW("C:\\Users\\hoang\\Desktop\\java\\Coffee\\temp.txt");
            tableUpdate();
        } catch (IOException ex) {
            Logger.getLogger(CashierForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(CashierForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void txtFindKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFindKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar()==KeyEvent.VK_ENTER)
        {
            String Find=txtFind.getText();
            System.out.println(Find);
             try {
            // TODO add your handling code here:
            ArrayList<ProductDTO> ListProduct=new ArrayList<>();
            String Category=boxCategory.getSelectedItem().toString();
            ProductDAL productDAL=new ProductDAL();
            ListProduct=productDAL.getProduct_Category(Category);
            DefaultTableModel d=(DefaultTableModel) tabProduct.getModel();
            d.setRowCount(0);  
            for(int i=0;i<ListProduct.size();i++)
            {
                String name=ListProduct.get(i).getName();
                String barcode=ListProduct.get(i).getBarcode();
                if(name.toLowerCase().contains(Find)||barcode.toLowerCase().contains(Find))
                {                                              
                         Vector v2=new Vector();
                         v2.add(ListProduct.get(i).getBarcode());
                         v2.add(ListProduct.get(i).getName());
                         v2.add(new ProductBLL().getSize(ListProduct.get(i).getSize()));
                         v2.add(ListProduct.get(i).getQty());
                         v2.add(ListProduct.get(i).getPrice());
                         d.addRow(v2);
                         
                }
            }
            
        } catch (Exception ex) {
            Logger.getLogger(CashierForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_txtFindKeyPressed

    private void txtNameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNameMouseEntered
        // TODO add your handling code here:
        txtName.setBackground(new Color(255,153,153));
    }//GEN-LAST:event_txtNameMouseEntered

    private void txtNameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNameMouseExited
        // TODO add your handling code here:
        txtName.setBackground(new Color(255,102,102));
    }//GEN-LAST:event_txtNameMouseExited

    private void txtNameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNameMousePressed
        // TODO add your handling code here:
        txtName.setBackground(new Color(255,204,255));
    }//GEN-LAST:event_txtNameMousePressed

    private void txtNameMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNameMouseReleased
        // TODO add your handling code here:
        txtName.setBackground(new Color(255,102,102));
    }//GEN-LAST:event_txtNameMouseReleased

    private void txtNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNameMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_txtNameMouseClicked

    private void btnHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryActionPerformed
        try {
            // TODO add your handling code here:
            panelMain.removeAll();
            panelMain.repaint();
            panelMain.add(panelHistory);
            panelMain.revalidate();
            ArrayList<BillDTO> ListBill=new BillDAL().getList();
            System.out.println(ListBill.get(2));
            updatetabHistory();
        } catch (Exception ex) {
            Logger.getLogger(CashierForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnHistoryActionPerformed

    private void btnExcelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcelMousePressed
        // TODO add your handling code here:
        ImageIcon image=new ImageIcon("C:\\Users\\hoang\\Desktop\\java\\Coffee\\src\\image\\icons8_microsoft_excel_100px_1.png");
        btnExcel.setIcon(image);
    }//GEN-LAST:event_btnExcelMousePressed

    private void btnExcelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcelMouseReleased
        // TODO add your handling code here:
        ImageIcon image=new ImageIcon("C:\\Users\\hoang\\Desktop\\java\\Coffee\\src\\image\\icons8_microsoft_excel_100px.png");
        btnExcel.setIcon(image);
    }//GEN-LAST:event_btnExcelMouseReleased

    private void btnHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistoryMouseClicked
        try {
            // TODO add your handling code here:
            updatetabHistory();
        } catch (Exception ex) {
            Logger.getLogger(CashierForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnHistoryMouseClicked

    private void btnPropertiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPropertiesActionPerformed
        try {
            // TODO add your handling code here:
            tabProperties();
        } catch (Exception ex) {
            Logger.getLogger(CashierForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPropertiesActionPerformed

    private void btnPDFMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPDFMousePressed
        // TODO add your handling code here:
        ImageIcon image=new ImageIcon("C:\\Users\\hoang\\Desktop\\java\\Coffee\\src\\image\\icons8_pdf_100px.png");
        btnPDF.setIcon(image);
    }//GEN-LAST:event_btnPDFMousePressed

    private void btnPDFMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPDFMouseReleased
        // TODO add your handling code here:
            ImageIcon image=new ImageIcon("C:\\Users\\hoang\\Desktop\\java\\Coffee\\src\\image\\icons8_pdf_100px_2.png");
            btnPDF.setIcon(image);
    }//GEN-LAST:event_btnPDFMouseReleased

    private void btnExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcelActionPerformed
        try {
            // TODO add your handling code here:
            ArrayList<BillDTO> ListBill=new BillDAL().getList();
            FileBLL file=new FileBLL();
            file.WriteFileExcel_Bills("C:\\Users\\hoang\\Desktop\\temp.xlsx", ListBill);
        } catch (Exception ex) {
            Logger.getLogger(CashierForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnExcelActionPerformed

    private void btnPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPDFActionPerformed
        // TODO add your handling code here:
        DefaultTableModel d=(DefaultTableModel) tabHistory.getModel();
        int selectIndex=tabHistory.getSelectedRow();
        System.out.println(d.getValueAt(selectIndex, 0).toString());
        String link="C:\\Users\\hoang\\Desktop\\java\\Coffee\\src\\coffee\\Form\\XuatHoaDon.jrxml";
        System.out.println(Integer.parseInt( d.getValueAt(selectIndex, 0).toString()));
        try {
            Class.forName("org.gjt.mm.mysql.Driver");
            String database="jdbc:mysql://localhost:3306/coffee";
            String us="root";
            String ps="";
            Connection conn=(Connection)DriverManager.getConnection(database,us,ps);
            HashMap<String,Object> map=new HashMap<>();
            JasperReport jr=JasperCompileManager.compileReport(link);
            map.put("BillId",Integer.parseInt( d.getValueAt(selectIndex, 0).toString()));
            JasperPrint jp=JasperFillManager.fillReport(jr,map,conn);
            
            JasperViewer.viewReport(jp,false);
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnPDFActionPerformed
    
    private void lblNotiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNotiMouseClicked
        // TODO add your handling code here:
        if(temp==1)
        {
            try {
                NotificationForm Noti=new NotificationForm();
                Noti.setVisible(true);
                Noti.setAlwaysOnTop(true);
                temp=0;
            } catch (Exception ex) {
                Logger.getLogger(CashierForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_lblNotiMouseClicked
    
    public void updateCategory() throws Exception{
        ArrayList<categoryDTO> List=new ArrayList<>();
        List=new categoryDAL().getCategoryListIsActive();
        for(int i=0;i<List.size();i++)
        {
            boxCategory.addItem(new categoryDTO(List.get(i).getId(), List.get(i).getStatus(),List.get(i).getCate_name()).getCate_name());
        }
    }
    public void updatetabProduct() throws Exception{
        DefaultTableModel d=(DefaultTableModel) tabProduct.getModel();
        int selectIndex=tabProduct.getSelectedRow();
        ArrayList<ProductDTO> ListProduct=new ArrayList<>();
        String Category=boxCategory.getSelectedItem().toString();
        ProductDAL productDAL=new ProductDAL();
        ListProduct=productDAL.getProduct_Category(Category);      
        d.setRowCount(0);
            for(int i=0;i<ListProduct.size();i++)
            {
                 Vector v2=new Vector();
                 v2.add(ListProduct.get(i).getBarcode());
                 v2.add(ListProduct.get(i).getName());
                 v2.add(new ProductBLL().getSize(ListProduct.get(i).getSize()));
                 v2.add(ListProduct.get(i).getQty());
                 v2.add(ListProduct.get(i).getPrice());
                 d.addRow(v2);
            }
    }
    public void updateNotiIcon() throws Exception{
        lblNotiIcon.setVisible(false);
        ArrayList<ProductDTO> ListProduct=new ProductDAL().getListProduct();
        for(int i=0;i<ListProduct.size();i++)
        {
            if(ListProduct.get(i).getQty()<=5)
            {
                lblNotiIcon.setVisible(true);
                break;
            }
        }
    }
    public static void tableUpdate() throws IOException{
        int tong=0;
        ArrayList<CartDTO> ListCart=new ArrayList<>();
        ListCart=new FileBLL().ReadFiletoList("C:\\Users\\hoang\\Desktop\\java\\Coffee\\temp.txt");
        DefaultTableModel d=(DefaultTableModel) tabAddToCart.getModel();
        d.setRowCount(0);
                for(int i=0;i<ListCart.size();i++)
                {
                    Vector v2=new Vector();
                    v2.add(ListCart.get(i).getBarcode());
                    v2.add(ListCart.get(i).getProductName());
                    v2.add(ListCart.get(i).getSize());
                    v2.add(ListCart.get(i).getNote());
                    v2.add(ListCart.get(i).getQty());
                    v2.add(ListCart.get(i).getTotal());
                    tong+=ListCart.get(i).getTotal();
                    d.addRow(v2);
                    System.out.println(v2);
                }
       txtSubTotal.setText(Integer.toString(tong));
    }
    public void updatetabHistory() throws Exception{
         DefaultTableModel d=(DefaultTableModel) tabHistory.getModel();
         int selectIndex=tabHistory.getSelectedRow();
         ArrayList<BillDTO> ListBill=new BillDAL().getList();
         d.setRowCount(0);
         for(int i=0;i<ListBill.size();i++)
         {
             Vector v2=new Vector();
             v2.add(ListBill.get(i).getId());
             v2.add(ListBill.get(i).getDate());
             v2.add(ListBill.get(i).getTotal());
             d.addRow(v2);
         }
    }
    public void tabProperties() throws Exception{
        DefaultTableModel d=(DefaultTableModel) tabHistory.getModel();
        int selectIndex=tabHistory.getSelectedRow();
        txtDate.setText((String) d.getValueAt(selectIndex, 1));
        txtTotal.setText(d.getValueAt(selectIndex, 2).toString());
        int id=Integer.parseInt(d.getValueAt(selectIndex, 0).toString());
        txtBillID.setText(Integer.toString(id));
        ArrayList<OrderDTO> ListOrder=new OrderDAL().getList();
        ArrayList<OrderDTO> ListTemp=new ArrayList<>();
        for(int i=0;i<ListOrder.size();i++)
        {
            if(id==ListOrder.get(i).getBill_id())
            {
                ListTemp.add(ListOrder.get(i));
            }
        }
        StaffDTO staff=new StaffDAL().getStaff(Integer.toString(ListTemp.get(0).getCashier_id()));
        txtCashierName.setText(staff.getFirstname()+" "+staff.getLastname());
        DefaultTableModel d2=(DefaultTableModel) tabProperties.getModel();
        d2.setRowCount(0);
        for(int i=0;i<ListTemp.size();i++)
        {
            Vector v2=new Vector();
            v2.add(ListTemp.get(i).getProduct());
            v2.add(ListTemp.get(i).getSize());
            v2.add(ListTemp.get(i).getQty());
            v2.add(ListTemp.get(i).getTotal());
            d2.addRow(v2);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashierForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashierForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashierForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashierForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    CashierForm form=new CashierForm(22);
                    form.setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(CashierForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    public static int temp=1;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelNotif;
    private javax.swing.JLabel abc;
    private javax.swing.JComboBox<String> boxCategory;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnExcel;
    private javax.swing.JButton btnHistory;
    private javax.swing.JButton btnManage;
    private javax.swing.JButton btnOrder;
    private javax.swing.JButton btnPDF;
    private javax.swing.JButton btnProperties;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblNoti;
    private javax.swing.JLabel lblNotiIcon;
    private javax.swing.JPanel panelHistory;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelManage;
    private javax.swing.JPanel panelOrder;
    private javax.swing.JPanel panelProperties;
    private static javax.swing.JTable tabAddToCart;
    private javax.swing.JTable tabHistory;
    private javax.swing.JTable tabProduct;
    private javax.swing.JTable tabProperties;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JLabel txtBillID;
    private javax.swing.JLabel txtCashierName;
    private javax.swing.JLabel txtDate;
    private javax.swing.JTextField txtFind;
    private static javax.swing.JLabel txtName;
    private javax.swing.JTextField txtPay;
    private static javax.swing.JLabel txtSubTotal;
    private javax.swing.JLabel txtTotal;
    // End of variables declaration//GEN-END:variables
}
